# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Heroku Registry'
        repository: 'osu-recognition/web'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'release'
        arguments: '--build-arg COMMIT_HASH=$(Build.SourceVersion) --build-arg VERSION=$(Build.SourceBranchName)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Heroku Registry'
        repository: 'osu-recognition/web'
        command: 'push'
        tags: 'release'

    - task: Bash@3
      displayName: "Heroku login"
      inputs:
        targetType: 'inline'
        script: '(
  echo "machine api.heroku.com"
  echo " login $(HEROKU_CREDENTIALS_EMAIL)"
  echo " password $(HEROKU_CREDENTIALS_PASSWORD)"
) >> ~/.netrc && heroku auth:login'
        noProfile: false
        noRc: false

    - task: Bash@3
      displayName: "Heroku login"
      inputs:
        targetType: 'inline'
        script: 'heroku container:login --verbose'
        noProfile: false
        noRc: false
    - task: Bash@3
      displayName: "Heroku deploy"
      inputs:
        targetType: 'inline'
        script: 'heroku container:release web -a osu-recognition'
        noProfile: false
        noRc: false