# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Heroku Registry'
        repository: 'osu-recognition/web'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'release'
        arguments: '--build-arg COMMIT_HASH=$(Build.SourceVersion) --build-arg VERSION=$(Build.SourceBranchName)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Heroku Registry'
        repository: 'osu-recognition/web'
        command: 'push'
        tags: 'release'
    - task: Bash@3
      displayName: "Heroku login"
      inputs:
        targetType: inline
        script: '(
  echo "$HEROKU_CREDENTIALS_EMAIL"
  echo "$HEROKU_CREDENTIALS_PASSWORD"
) | heroku login'
    - task: Bash@3
      displayName: "Heroky deploy"
      inputs:
        targetType: inline
        script: 'heroku container:release web -a osu-recognition'